drop table if exists tb_member cascade;
create table tb_member (
    seq bigint generated by default as identity,
    login_id varchar(50) not null unique,
    password varchar(100) not null,
    name varchar(50) not null,
    token_version bigint not null default 0,
    primary key (seq)
);